import CreatedOnIcon from "../assets/calendar.svg";
import HashtagIcon from "../assets/hash.svg";
import PlayerIcon from "../assets/player.svg";
import StatusIcon from "../assets/status.svg";

export const WaitlistTableHeader = [
  { tableHeaderIcon: CreatedOnIcon, tabledHeaderName: "Created On" },
  { tableHeaderIcon: PlayerIcon, tabledHeaderName: "Player" },
  { tableHeaderIcon: StatusIcon, tabledHeaderName: "Status" },
  { tableHeaderIcon: HashtagIcon, tabledHeaderName: "Email" },
  { tableHeaderIcon: HashtagIcon, tabledHeaderName: "Player Phone" },
  { tableHeaderIcon: HashtagIcon, tabledHeaderName: "Services" },
  { tableHeaderIcon: CreatedOnIcon, tabledHeaderName: "Scheduled" },
];

export const WaitlistTableData = [
  {
    createdOn: "Sat, 07 Jan 2024 2:44 PM",
    payer: "Theodore TA Calvin",
    status: "Active",
    email: "theodore@example.com",
    phone: "+91 0000000000",
    service: "Private Language Session",
    scheduled: "Sat, 07 Jan 2024 2:44 PM",
  },
  {
    createdOn: "Sat, 07 Jan 2024 2:44 PM",
    payer: "Theodore TA Calvin",
    status: "Active",
    email: "theodore@example.com",
    phone: "+91 0000000000",
    service: "Private Language Session",
    scheduled: "Sat, 07 Jan 2024 2:44 PM",
  },
  {
    createdOn: "Sat, 07 Jan 2024 2:44 PM",
    payer: "Theodore TA Calvin",
    status: "Active",
    email: "theodore@example.com",
    phone: "+91 0000000000",
    service: "Private Language Session",
    scheduled: "Sat, 07 Jan 2024 2:44 PM",
  },
  {
    createdOn: "Sat, 07 Jan 2024 2:44 PM",
    payer: "Theodore TA Calvin",
    status: "Inactive",
    email: "theodore@example.com",
    phone: "+91 0000000000",
    service: "Private Language Session",
    scheduled: "Sat, 07 Jan 2024 2:44 PM",
  },
  {
    createdOn: "Sat, 07 Jan 2024 2:44 PM",
    payer: "Theodore TA Calvin",
    status: "Active",
    email: "theodore@example.com",
    phone: "+91 0000000000",
    service: "Private Language Session",
    scheduled: "Sat, 07 Jan 2024 2:44 PM",
  },
  {
    createdOn: "Sat, 07 Jan 2024 2:44 PM",
    payer: "Theodore TA Calvin",
    status: "Inactive",
    email: "theodore@example.com",
    phone: "+91 0000000000",
    service: "Private Language Session",
    scheduled: "Sat, 07 Jan 2024 2:44 PM",
  },
  {
    createdOn: "Sat, 07 Jan 2024 2:44 PM",
    payer: "Theodore TA Calvin",
    status: "Active",
    email: "theodore@example.com",
    phone: "+91 0000000000",
    service: "Private Language Session",
    scheduled: "Sat, 07 Jan 2024 2:44 PM",
  },
  {
    createdOn: "Sat, 07 Jan 2024 2:44 PM",
    payer: "Theodore TA Calvin",
    status: "Inactive",
    email: "theodore@example.com",
    phone: "+91 0000000000",
    service: "Private Language Session",
    scheduled: "Sat, 07 Jan 2024 2:44 PM",
  },
  {
    createdOn: "Sat, 07 Jan 2024 2:44 PM",
    payer: "Theodore TA Calvin",
    status: "Inactive",
    email: "theodore@example.com",
    phone: "+91 0000000000",
    service: "Private Language Session",
    scheduled: "Sat, 07 Jan 2024 2:44 PM",
  },
  {
    createdOn: "Sat, 07 Jan 2024 2:44 PM",
    payer: "Theodore TA Calvin",
    status: "Inactive",
    email: "theodore@example.com",
    phone: "+91 0000000000",
    service: "Private Language Session",
    scheduled: "Sat, 07 Jan 2024 2:44 PM",
  },
  {
    createdOn: "Sat, 07 Jan 2024 2:44 PM",
    payer: "Theodore TA Calvin",
    status: "Lead",
    email: "theodore@example.com",
    phone: "+91 0000000000",
    service: "Private Language Session",
    scheduled: "Sat, 07 Jan 2024 2:44 PM",
  },
  {
    createdOn: "Sat, 07 Jan 2024 2:44 PM",
    payer: "Theodore TA Calvin",
    status: "Active",
    email: "theodore@example.com",
    phone: "+91 0000000000",
    service: "Private Language Session",
    scheduled: "Sat, 07 Jan 2024 2:44 PM",
  },
  {
    createdOn: "Sat, 07 Jan 2024 2:44 PM",
    payer: "Theodore TA Calvin",
    status: "Lead",
    email: "theodore@example.com",
    phone: "+91 0000000000",
    service: "Private Language Session",
    scheduled: "Sat, 07 Jan 2024 2:44 PM",
  },
];
